---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
popn <- read_csv("data/popn_race_age_us_census_estimate_2019.csv")
```

```{r}
colnames(popn)
```

```{r}
popn <- popn %>% 
  filter(ORIGIN != 0) %>%  
    filter(SEX != 0) 
  
```

```{r}
popn <- popn %>% 
  select("SUMLEV", "REGION", "DIVISION", "STATE", "NAME", "SEX", "ORIGIN", "RACE", "AGE", "POPESTIMATE2019")
```

```{r}
popn %>% 
  summarise(sum(POPESTIMATE2019))
```


```{r}
hispanic <- popn %>% 
  select(NAME, ORIGIN, POPESTIMATE2019) %>% 
  janitor::clean_names() %>% 
  mutate(origin = ifelse(origin ==1, "not_hispanic", "is_hispanic"))
  
```

```{r}
hispanic <- hispanic %>% 
  rename(state = name)
```

```{r}
colnames(hispanic)
```

```{r}
hispanic_yes_no <- hispanic %>% 
  group_by(state, origin) %>% 
  summarise(sum = sum(popestimate2019))
```
```{r}
hispanic_yes_no <- hispanic_yes_no %>% 
  pivot_wider(names_from = origin, values_from = sum)
```

```{r}
sum(hispanic_yes_no$not_hispanic)
```

```{r}

kerr_data <- read_csv("data/kerr_us_data.csv")
```

```{r}
colnames(kerr_data)
```

```{r}
kerr_data_master <- left_join(kerr_data, hispanic_yes_no)
```

```{r}
colnames(kerr_data_master)
```
```{r}
unique(kerr_data_master$state)
```

```{r}
kerr_data_master <- kerr_data_master %>% 
  mutate(total_popn = is_hispanic + not_hispanic)
```

```{r}
ages <- read_csv("data/ages.csv")
education <- read_csv("data/education.csv")
kerr_data_master <- left_join(kerr_data_master, education)
kerr_data_master <- left_join(kerr_data_master, ages)


```

```{r}
results <- read_csv("data/result2016_2020/2020result_party.csv")
s2016 <- read_csv("data/result2016_2020/states_2016_2020.csv")
kerr_data_master <- left_join(kerr_data_master, results)
kerr_data_master <- left_join(kerr_data_master, s2016)
```

```{r}
colnames(kerr_data_master)
```

```{r}
kerr_data_master <- kerr_data_master %>% 
rename("adults_65plus" = "65+") %>% 
  rename(party2020 = X2) 
```

```{r}
kerr_data_master <- kerr_data_master %>% 
  rename(adult_gun_at_home_perc = adults_with_at_least_1_gun_at_home_2019) %>% 
  mutate(health_insured_2019_any_coverage = (health_insured_2019_any_coverage* 1000)) %>% 
  mutate(health_insured_2019_uninsured = (health_insured_2019_uninsured*1000))
```

```{r}
View(kerr_data_master)
```



```{r}
david <- read_csv("data/cleaning/dw_final_stats.csv")
conor <- read_csv("data/cleaning/clean_state_pop3.csv") %>% 
  rename(state = State)
kerr_data_master <- left_join(kerr_data_master, david)
kerr_data_master <- left_join(kerr_data_master, conor)
```

```{r}
kerr_data_master <- kerr_data_master %>% 
  janitor::clean_names()
```

```{r}
kerr_data_master %>% 
write_csv("data/master_data_final.csv")
```

